# Generated by Django 3.2.4 on 2021-07-31 09:25

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deviceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceKey', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='设备Key')),
                ('deviceValue', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='设备类型')),
                ('devlogo', models.ImageField(blank=True, null=True, upload_to=app.models.newImageName, verbose_name='设备LOGO')),
                ('deviceState', models.CharField(blank=True, choices=[(0, '禁用'), (1, '启用')], default='0', max_length=255, null=True, verbose_name='是否禁用')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '网络设备类型',
                'verbose_name_plural': '网络设备类型',
            },
        ),
        migrations.CreateModel(
            name='loginUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='密码')),
                ('userstate', models.BooleanField(blank=True, default=False, null=True, verbose_name='登录权限只读/写入')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '网络设备登录用户',
                'verbose_name_plural': '网络设备登录用户',
            },
        ),
        migrations.CreateModel(
            name='networkOpenAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=app.models.getnumber, max_length=255, null=True, verbose_name='编号')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='名称')),
                ('appid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='应用ID')),
                ('appsecret', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='应用密钥')),
                ('redirectUrl', models.URLField(blank=True, default='', max_length=255, null=True, verbose_name='回调地址')),
                ('ipwhitelist', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='IP白名单')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='手机通知')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱通知')),
                ('enabled', models.BooleanField(blank=True, default=False, max_length=255, null=True, verbose_name='是否禁用')),
                ('desc', models.TextField(blank=True, default='', max_length=500000, verbose_name='备注')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '网络服务API',
                'verbose_name_plural': '网络服务API',
            },
        ),
        migrations.CreateModel(
            name='networkOpenAPIList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(blank=True, default='', max_length=255, verbose_name='开始时间')),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IP')),
                ('resultText', models.TextField(blank=True, default='[]', max_length=500000, verbose_name='运行结果Json')),
                ('cmdInfo', models.TextField(blank=True, default='[]', max_length=500000, verbose_name='运行结果')),
                ('taskStatus', models.CharField(choices=[(0, '待处理'), (1, '处理中'), (2, '已完成'), (-1, '执行失败')], default='待处理', max_length=255, verbose_name='任务状态')),
                ('exceptionInfo', models.TextField(blank=True, default='', max_length=500000, verbose_name='异常信息')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
                ('networkopenapi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.networkopenapi', verbose_name='网络服务API')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
            },
        ),
        migrations.CreateModel(
            name='networkOpenTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('tempstate', models.BooleanField(blank=True, default=False, null=True, verbose_name='操作范围(只读/写入)')),
                ('cmds', models.TextField(blank=True, default='', max_length=500000, verbose_name='CMDS')),
                ('desc', models.TextField(blank=True, default='', max_length=500000, verbose_name='备注')),
                ('useCount', models.IntegerField(default=0, verbose_name='使用次数')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '接口场景',
                'verbose_name_plural': '接口场景',
            },
        ),
        migrations.CreateModel(
            name='networkOpenAPIListKwargs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='参数名称')),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='参数值')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
                ('networkopenapilist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.networkopenapilist', verbose_name='任务列表')),
            ],
            options={
                'verbose_name': '扩展参数',
                'verbose_name_plural': '扩展参数',
            },
        ),
    ]
